### PR TITLE
Enable documentation build again

### PR DESCRIPTION
**Pull request by huiyuxie**

### CODE REVIEW

**Comment by ErikQQY** [comment]
There are some issues with the latest Julia 1.11 in CI, so just sticking with 1.10 could avoid them

**Comment by huiyuxie** [comment]
> There are some issues with the latest Julia 1.11 in CI

Thanks @ErikQQY! Could you refer me to the issue?

**Comment by ErikQQY** [comment]
The failing CI error about failed to compile several packages on 1.11: https://github.com/trixi-gpu/TrixiCUDA.jl/actions/runs/11230724218/job/31218629742, I met a similar error a few weeks ago. But if you want to upgrade to 1.11, we can try forcing the compats to the latest version and see how it goes(I suspect the outdated compats are the reason why CI failing).

**Comment by huiyuxie** [comment]
Thanks! Downgrading is good 👍

**Pull request merged**
